<h2><?php //print_r($this->api); ?></h2>

<br><br><br><br>
<a href="<?php echo $this->url(array('controller' => 'api',
            'action' => 'nuevo')); ?>">
    <h3>Nuevo contacto</h3>
            </a>
<table border="1">
    <?php foreach ($this->api as $d) : ?>


        <!--           por cada fila, muestro sus datos -->
        <tr>
            <!--            nombre del album, con un enlace para editar el album-->
            <td>

                </a>
            </td>
            <!--                id del artista-->
            <td><?php echo $this->escape($d->id); ?></td>
            <!--                    fecha del album-->
            <td>
                 <a href="<?php echo $this->url(array('controller' => 'api',
            'action' => 'encontrar', 'id' => $d->id)); ?>">
                   <?php echo $this->escape($d->name); ?>
            </a>
                
            </td>
            <!--                        descripcion-->
            <td><?php echo $this->escape($d->identification); ?></td>

            <!--                        descripcion-->
            <td><?php echo $this->escape($d->email); ?></td>
            <!--                   enlace para borrar el album-->
            <td><?php echo $this->escape($d->phonePrimary); ?></td>
            <td><?php echo $this->escape($d->phoneSecondary); ?></td>
            <td><?php echo $this->escape($d->fax); ?></td>
            <td><?php echo $this->escape($d->mobile); ?></td>
            <td><?php echo $this->escape($d->observations); ?></td>
            <td><?php
                echo $d->address->address;
                echo " ";
                echo $this->escape($d->address->city);
                ?></td>

            <td>
                <?php foreach ($d->type as $tipo): ?>

                    <?php echo $this->escape($tipo); ?>
                <?php endforeach; ?>
            </td>
<td>
                <?php if ($d->seller) { ?>

            <?php echo $this->escape($d->seller->name); ?>
<?php } ?>
</td>
            <td><?php echo $this->escape($d->term->name); ?></td>

            <td>
                <?php if ($d->priceList) { ?>

                    <?php echo $this->escape($d->priceList->name); ?>

                <?php } ?>
            </td>
            <td>
                <?php foreach ($d->internalContacts as $contactos): ?>

                    <?php echo $this->escape($contactos->name); ?>
                <?php endforeach; ?>
            </td>
            <td>

                <a href="<?php
                echo $this->url(array('controller' => 'api',
                    'action' => 'delete', 'id' => $d->id));
                ?>">Delete</a>
            </td>
        </tr>
        <!--    fin del for-->

    <?php endforeach; ?>
</table>
<?php
